### ISSUE TITLE
这个音频合成的Demo导入Android Studio之后运行后点击录音会报错

### ISSUE THREAD

**Issue by 1294694985** [CrazyZty/ComposeAudio#1]
![image](https://cloud.githubusercontent.com/assets/17264211/21416358/3440f678-c84d-11e6-9b05-0cc8818b6825.png)

**Comment by CrazyZty** [comment]
后面的AppLog开始的是我自己写的输出外文件log错误，你先添加应用的写外文件全权限。
另外前面的错误上传文字吧，不要截图，

**Comment by maomaohang2013** [comment]
android6.0之後，讀寫權限需要動態申請，不想麻煩的話 targetSdkVersion 改為23以下就可以運行了。。。
